# Configuraci\u00F3n del Servidor
spring.application.name=campusFlow

# Base de Datos (Toma Supabase/PostgreSQL en Render y MySQL en local)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/campus_flow}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

# Configuraci\u00F3n JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Clave Secreta JWT
JWT_SECRET=${JWT_SECRET:claveSecretaSuperSeguraParaDesarrolloLocal123456}

# Configuraci\u00F3n de Stripe
stripe.secret-key=${stripe.secret-key}
stripe.webhook-secret=${stripe.webhook-secret}
stripe.price-pago-unico=${stripe.price-pago-unico}
stripe.price-plan-individual=${stripe.price-plan-individual}
stripe.url-exito=http://localhost:8080/pago-exitoso
stripe.url-cancelado=http://localhost:8080/pago-cancelado

server.port=${PORT:8080}